### PR TITLE
Shorten video+update CC license

### PR DESCRIPTION
**Pull request by cooperrc**
adding @labarba and @ncclementi to CC licenses in pages

shortening catch motion to 1 video and adding it to repo (no download command)

### CODE REVIEW

**Comment by ncclementi** [comment]
@cooperrc I'm not quite sure what's going on here, but if what you are trying to do is give attribution to the material that @labarba and myself wrote. I believe the right way to do this is something like what I put below, where you give attribution to the original and then add your modifications under your name. For example:

> This work is based on:
> - (c) 2017 Lorena A. Barba, Natalia C. Clementi. All content is under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode.txt), and all [code is under BSD-3 clause](https://github.com/engineersCode/EngComp/blob/master/LICENSE). Original content available at [link to the original work].
> - Modifications and additional content (c) 2020 Ryan Copper. Licensed under Creative Commons Attribution CC BY 4.0 
  (if you modified the code then include your BSD3 too)

**Comment by labarba** [comment]
Yes... unfortunately there's widespread confusion about the attribution obligations of licensed materials. One has to actually read through the long text of CC licenses to find the relevant bits, and most of us don't. But the conditions are explicit:

> If You Share the Licensed Material (including in modified form), You must: (a) retain the following if it is supplied by the Licensor with the Licensed Material: identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor […]; a copyright notice; a notice that refers to this Public License; a notice that refers to the disclaimer of warranties; a URI or hyperlink to the Licensed Material to the                     extent reasonably practicable; (b) indicate if You modified the Licensed Material and retain an indication of any previous modifications; and (c) indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.

Quite verbose, but the main point is that one should preserve the original Copyright notice in full, mention the license, and include a link to it. You are not obligated to but it's nice to include a link to the original material.

**Comment by cooperrc** [comment]
OK, thanks @ncclementi and @labarba !

I am updating course content for Winter and wanted to make sure I gave better attribution. I can add a link to the material and @ncclementi 's license in another PR.

**Comment by labarba** [comment]
Side note: I did lots of updates to the original materials this past semester.

**Comment by cooperrc** [comment]
> Side note: I did lots of updates to the original materials this past semester.

Awesome! I point dozens of students to your resources every semester. I especially love the phugoid numerical methods.

**Pull request merged**
